Fix a violated precondition in `result_buffer_to_string()` in newer rustc versions
Can be reproduced e.g. by running tests:

    thread 'hash_accepts_str_as_bytes' (172174) panicked at src/lib.rs:283:24:
    unsafe precondition(s) violated: slice::get_unchecked requires that the
    index is within the slice

    This indicates a bug in the program. This Undefined Behavior check is
    optional, and cannot be relied on for safety.